export const TOGGLE_NAVBAR = 'TOGGLE_NAVBAR';

export const DISPLAY_ALERT = 'DISPLAY_ALERT';
export const CLEAR_ALERT = 'CLEAR_ALERT';

export const CLEAR_VALUES = 'CLEAR_VALUES';

export const HANDLE_CHANGE = 'HANDLE_CHANGE';
export const HANDLE_CHANGE_OTHERS = 'HANDLE_CHANGE_OTHERS';
export const HANDLE_CHECKBOX_CHANGE = 'HANDLE_CHECKBOX_CHANGE';

export const BEGIN_REGISTER_USER = 'BEGIN_REGISTER_USER';
export const SUCCESS_REGISTER_USER = 'SUCCESS_REGISTER_USER';
export const ERROR_REGISTER_USER = 'ERROR_REGISTER_USER';

export const ADD_OTHER_GUEST = 'ADD_OTHER_GUEST';

export const DELETE_OTHER_GUEST = 'DELETE_OTHER_GUEST';
